(library
 (name await_test)
 (public_name await.test)
 (ocamlopt_flags :standard -regalloc-param SPLIT_LIVE_RANGES:off)
 (libraries async await await_blocking await_in_async await_spinning
   core_kernel.caml_threads concurrent concurrent.in_async
   concurrent.in_thread core core_unix.core_thread core_unix
   expect_test_helpers_core.expect_test_helpers_base expect_test_helpers_core
   parallel parallel.scheduler.work_stealing portable threads)
 (preprocess
  (pps ppx_jane ppx_quick_test ppx_with)))
